### ISSUE TITLE
TileMatrix issues under Mono

### ISSUE THREAD

**Issue by vapaa** [kamronbatman/ModernUO#11]
This line is not compiled under mono.
NativeReader.Read( m_Statics.Handle, pTiles, length );

**Comment by kamronbatman** [comment]
Thank you @vapaa, I will take a look!
Also please let me know what version of Mono, since I regularly compile with Mono and it works.

**Comment by kamronbatman** [comment]
@vapaa, can you provide me with the version of Mono you used?

**Comment by kamronbatman** [comment]
@vapaa, I think I got this fixed. Please test and let me know! Thanks.
